# Generated by Django 4.0.4 on 2022-05-26 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Friends', '0003_friendlist_friendrequest_delete_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='user',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='request_receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='request_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendlist',
            name='request_sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
